# Generated by Django 5.0.2 on 2024-03-29 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articleview",
            unique_together={("article", "user", "viewer_ip")},
        ),
    ]
